//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapeamentoEcossistema.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public int Id { get; set; }
        public int QuestionGroupId { get; set; }
        public string Title { get; set; }
        public short SortOrder { get; set; }
    
        public virtual QuestionGroup QuestionGroup { get; set; }
        public virtual ICollection<Response> Responses { get; set; }
    }
}
