//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapeamentoEcossistema.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionGroup
    {
        public QuestionGroup()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int Id { get; set; }
        public int QuestionnaireId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public short SortOrder { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
